### ISSUE TITLE
add my instance

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [ticky/wayback-classic#15]
https://waybackclassic.esmailelbob.xyz/
and for tor: http://waybackclassic.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion/

**Comment by EsmailELBoBDev2** [comment]
I usually open PR with updated README.md but I can't find where you save list of instances

**Comment by sjehuda** [comment]
I suggest you use README.md or suggest a file for instances.

I'll add your instance to [Proxy Redirect](https://openuserjs.org/scripts/sjehuda/Proxy_Redirect) when support for Wayback Classic be added.

**Comment by sjehuda** [comment]
I suggest you add instances to README.md or suggest a file for instances.

_P.S. I'll add your instance to [Proxy Redirect](https://openuserjs.org/scripts/sjehuda/Proxy_Redirect) when I add support for Wayback Classic._

**Comment by ticky** [comment]
> list of instances

sorry, I am not interested in maintaining one. technically it isn't even licensed for that use, though that is likely to change.

> P.S. I'll add your instance to [Proxy Redirect](https://openuserjs.org/scripts/sjehuda/Proxy_Redirect) when I add support for Wayback Classic.

wayback-classic is _not_ a proxy; everything it allows access to is coming directly from the wayback machine

**Comment by EsmailELBoBDev2** [comment]
> sorry, I am not interested in maintaining one. technically it isn't even licensed for that use, though that is likely to change.

Sad to hear but alright!
