### ISSUE TITLE
Add Dillo

### ISSUE THREAD

**Issue by sjehuda** [ticky/wayback-classic#19]
Please add a banner to [Dillo Web Browser](https://www.dillo.org/) which seems to be qualified for older websites.

**Comment by ticky** [comment]
Dillo doesn't even seem to be available for download, let alone fit the y2k throwback vibe of the footer

**Comment by sjehuda** [comment]
Dillo is available for Linux, and I assume for Windows too.

The "y2k" style is mostly the banner style, not the logo, no?
