### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by fd1f** [ticky/wayback-classic#21]
Without a license, nobody is covered if they use, share, or modify the project. Maybe they'll do all three! Please consider choosing one.

I don't know what license you would choose, but I think [Choose a License](https://choosealicense.com)  is a good resource for some pointers.

**Comment by oifj34f34f** [comment]
Will this project have a license? If not, it would be nice to clarify this to close this issue

**Comment by leoheitmannruiz** [comment]
Not the author, but perhaps see https://github.com/ticky/wayback-classic/pull/22#issuecomment-1627789186

**Comment by ticky** [comment]
I have pushed up a change adding the AGPL license to the project. Thanks for your patience.

**Comment by leoheitmannruiz** [comment]
Cool! Love to see markdown versions of licenses 😁
