### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by oifj34f34f** [ticky/wayback-classic#24]
Error: Couldn't retrieve date index for this URL

**Comment by ticky** [comment]
Hi @oifj34f34f, could you give me some more info? What URL were you trying to look up? Around what time were you doing so?

**Comment by oifj34f34f** [comment]
@ticky Actually any, such as `https://www.google.com`. Just tried it and it still doesn't work (I'm using https://wayback-classic.net/ but it also doesn't work on localhost)
![20231118_21h15m37s_grim](https://github.com/ticky/wayback-classic/assets/128177553/f5b414b3-60b4-43b4-9fab-4accc1fc0505)

**Comment by oifj34f34f** [comment]
It seems to be working now :-)
